### ISSUE TITLE
User Story #1:

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/my-journal-app#4]
# Solve first puzzle

## Value proposition

As a player
I want to see my first puzzle
So that I can solve it.

## Description

![Image](https://user-images.githubusercontent.com/124199994/229153183-56a9bda3-f900-4697-971f-6023358f303c.png)

## Acceptance criteria

- [ ] A clue is displayed
- [ ] Code is displayed
- [ ] Area with 3 fields where you can select a color
  - [ ] in each field you can choose between 8 colors: yellow, brown, blue, red, green, purple, orange, gray 

## Tasks

- [ ] Create a paragraph with the clue "Gebe den Code ein"
- [ ]  display the color code with symbols inside
- [ ] Create a formfield with symbols and color field
